
// Errors
#define ERR_CHANNELISFULL   471
#define ERR_NOTONCHANNEL    442
#define ERR_NOSUCHCHANNEL   403
#define ERR_NEEDMOREPARAMS  461
#define ERR_NICKNAMEINUSE   433
#define ERR_NONICKNAMEGIVEN 431
#define ERR_NEEDMOREPARAMS  461
#define ERR_PASSWDMISMATCH  464
#define ERR_NOSUCHNICK 401
// Replies