
// Replies
#define RPL_INVITING        341

// Errors
#define ERR_NOSUCHNICK      401
#define ERR_NOSUCHCHANNEL   403
#define ERR_CANNOTSENDTOCHAN 404
#define ERR_NONICKNAMEGIVEN 431
#define ERR_NICKNAMEINUSE   433
#define ERR_USERNOTINCHANNEL 441
#define ERR_NOTONCHANNEL    442
#define ERR_USERONCHANNEL   443
#define ERR_NEEDMOREPARAMS  461
#define ERR_ALREADYREGISTERED 462
#define ERR_PASSWDMISMATCH  464
#define ERR_CHANNELISFULL   471
#define ERR_INVITEONLYCHAN  473
#define ERR_BADCHANNELKEY   475
#define ERR_CHANOPRIVSNEEDED 482